config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'users#new'
  # root "/LP"
  get '/lp', to: redirect('/lp.html')

  resources :items
  resources :cordinates
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  resources :microposts, only: %i[create destroy]
  resources :relationships, only: %i[create destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  resources :relationships, only: %i[create destroy]
  resources :blocks, only: %i[create destroy]

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :users do
    member do
      get :blocking, :blockers
    end
  end

  delete '/logout', to: 'sessions#destroy'
  get 'search', to: 'items#search'
  get '/help', to: 'static_pages#help'
  get '/home', to: 'static_pages#home'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  # かんたんログインの実装
  post '/sessions/guest_log_in', to: 'sessions#guest_login', as: 'guest_login'
  # 全てのUserのItemとCordinateをみる
  get '/:user_id/cordinates/allusers', to: 'cordinates#all_cordinate_show',
                                       as: 'all_cordinate_show'
  get '/:user_id/items/allusers', to: 'items#all_item_show', as: 'all_item_show'

  # Rasnsackで全てのUserのItemをみる
  get '/:user_id/items/items_search/tpo', to: 'items#all_item_tpo_search',
                                          as: 'items_tpo_search'
  get '/:user_id/items/items_search/rating',
      to: 'items#all_item_rating_search', as: 'items_rating_search'
  get '/:user_id/items/items_search/season',
      to: 'items#all_item_season_search', as: 'items_serch_season'
  get '/:user_id/items/items_search/color', to: 'items#all_item_color_search',
                                            as: 'items_search_color'
  get '/:user_id/items/items_search/super_item',
      to: 'items#all_item_super_item_search', as: 'items_search_super_item'

  # Rasnsackで全てのUserのCordinateをみる
  get '/:user_id/cordinates/cordinates_search/tpo', to: 'cordinates#all_cordinate_tpo_search',
                                                    as: 'cordinates_tpo_search'
  get '/:user_id/cordinates/cordinates_search/season', to: 'cordinates#all_cordinate_season_search',
                                                       as: 'cordinates_season_search'
  get '/:user_id/cordinates/cordinates_search/rating', to: 'cordinates#all_cordinate_rating_search',
                                                       as: 'cordinates_rating_search'

  get '/:user_id/items/cordinates_search',
      to: 'cordinates#all_cordinate_search', as: 'cordinates_serch'

  # userコントローラー
  get '/users/:user_id/index', to: 'users#index', as: 'allusers_index'
  get '/users/new', to: 'users#new', as: 'user_new'
  get '/users/:id/', to: 'users#show', as: 'user_show'
  # get '/users/:id/ranking', to: 'users#ranking', as: 'user_ranking'

  # itemsコントローラー(個別User)
  get '/users/:user_id/items/all', to: 'items#user_all_item_show',
                                   as: 'user_item'
  get '/users/:user_id/items/new', to: 'items#new', as: 'item_new'
  get '/users/:user_id/items/:id', to: 'items#show', as: 'item_show'
  patch '/users/:user_id/items/:id/edit', to: 'items#update', as: 'item_update'
  get '/users/:user_id/items/:id/edit', to: 'items#edit', as: 'item_edit'
  get '/users/:user_id/cordinates/:cordinate_id/items',
      to: 'items#cordinate_show', as: 'cordinate_item_show'
  get '/users/:user_id/cordinates/:cordinate_id/items/search', to: 'items#cordinate_search_si',
                                                               as: 'cordinate_search_si'
  post '/users/:user_id/items/', to: 'items#create', as: 'item_create'
  delete '/users/:user_id/items/:id', to: 'items#destroy', as: 'item_delete'

  # cordinateコントローラー(個別のUser)
  get '/users/:user_id/cordinates/all',
      to: 'cordinates#user_all_cordinate_show', as: 'user_cordinate'
  get '/users/:user_id/cordinates/new', to: 'cordinates#new', as: 'cordinate_new'
  get '/users/:user_id/cordinates/:id', to: 'cordinates#show',
                                        as: 'cordinate_show'
  get '/users/:user_id/cordinates/:id/edit', to: 'cordinates#edit',
                                             as: 'cordinate_edit'
  post '/users/:user_id/cordinates/', to: 'cordinates#create',
                                      as: 'cordinate_create'

  # get '/users/:user_id/cordinates/:id/modal', to: 'cordinates#cordinate_modal',

  # saveに関してリファクタリングの可能性を検討する
  get '/users/:user_id/cordinates/:id/items/:item_id/edit',
      to: 'cordinates#item_edit', as: 'cordinate_item_edit'

  # controllerを変える必要はあるのか？
  patch '/users/:user_id/cordinates/:id/', to: 'cordinates#update',
                                           as: 'cordinate_patch'
  delete '/users/:user_id/cordinates/:id', to: 'cordinates#destroy',
                                           as: 'cordinate_delete'
  patch '/users/:user_id/cordinates/:id/items/:item_id',
        to: 'cordinates#item_update', as: 'items_patch'

  # Commentシリーズ(個別のUser)
  post '/users/:user_id/cordinates/:id/comments', to: 'comments#create',
                                                  as: 'comment_create'
  delete '/users/:user_id/cordinates/:id/comments/:comment_id',
         to: 'comments#destroy', as: 'comment_delete'

  # Likecordinateシリーズ(個別のUser)
  post '/users/:user_id/cordinates/:id/likecordinates',
       to: 'likecordinates#create', as: 'likecordinate_create'
  delete '/users/:user_id/cordinates/:id/likecordinates/:likecordinate_id', to: 'likecordinates#destroy',
                                                                            as: 'likecordinate_delete'
  # Notificationsコントローラー(個別のUser)
  get '/users/:user_id/notifications/', to: 'notifications#index',
                                        as: 'notifications'
  delete '/users/notifications/alldelete', to: 'notifications#destroy_all',
                                           as: 'destroy_all_users_notifications'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  before_save :downcase_email
  before_create :create_activation_digest
  mount_uploader :picture, PictureUploader

  validates :name, presence: true, length: { maximum: 20 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password_digest, presence: true, length: { minimum: 6 },
                              allow_nil: true
  validates :password, presence: true
  attr_accessor :remember_token, :activation_token, :reset_token

  has_secure_password
  has_many :cordinates, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :likecordinates, dependent: :destroy
  has_many :blocks, dependent: :destroy

  # 通知機能の実装
  has_many :active_notifications, class_name: 'Notification',
                                  foreign_key: 'sender_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification',
                                   foreign_key: 'receiver_id', dependent: :destroy

  # ブロック機能の実装
  has_many :active_blocks, class_name: 'Block', foreign_key: 'blocker_id',
                           dependent: :destroy
  has_many :passive_blocks, class_name: 'Block', foreign_key: 'blocked_id',
                            dependent: :destroy

  has_many :blocking, through: :active_blocks, source: :blocked

  def already_liked?(_cordinate)
    cordinate = @cordinate
    likecordinates.exists?(cordinate_id: cordinate_id)
  end

  has_many :active_relationships, class_name: 'Relationship',
                                  foreign_key: 'follower_id',
                                  dependent: :destroy

  has_many :passive_relationships, class_name: 'Relationship',
                                   foreign_key: 'followed_id',
                                   dependent: :destroy

  # :sourceパラメーター を使って、following配列の元はfolledのidの集合体であることを明示する
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  # commentlikeの実装
  has_many :active_likecordinates, class_name: 'Likecordinate',
                                   foreign_key: 'user_id',
                                   dependent: :destroy

  has_many :liked_cordinates, through: :likecordinates, source: :cordinate
  has_many :commented_cordinates, through: :comments, source: :cordinate

  def block(other_user)
    active_blocks.create(blocked_id: other_user.id)
  end

  def unblock(other_user)
    active_blocks.find_by(blocked_id: other_user.id).destroy
  end

  def blocking?(user)
    blocking.include?(user)
  end

  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def comment_delete(other_user)
    comments.find_by(user_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

  # 渡された文字列のハッシュ値を返す
  def self.digest(string)
    cost = if ActiveModel::SecurePassword.min_cost
             BCrypt::Engine::MIN_COST
           else
             BCrypt::Engine.cost
           end
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(remember_token)
    return false if remember_digest.nil?

    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  # かんたんログインの実装
  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

  # メールアドレスをすべて小文字にする
  def downcase_email
    self.email = email.downcase
  end

  # パスワードが正規表現を満たすか確認する
  def password_regex
    valid_password_regex = /\A(?=.*?[a-z])(?=.*?[A-Z])(?=.*?\d)\w{10,20}\z/.freeze
    return nil if valid_password_regex.match(password)

    errors.add(:password, 'は半角10~20文字英大文字・小文字・数字をそれぞれ１文字以上含む必要があります')
  end

  # 有効化トークンとダイジェストを作成および代入する
  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_token)
  end

  # アカウントを有効にする
  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  # 有効化用のメールを送信する
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  # パスワード再設定の属性を設定する
  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest, User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # パスワード再設定のメールを送信する
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # パスワード再設定の期限が切れている場合はtrueを返す
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  # フォロー通知機能
  def create_notification_follow!(current_user)
    temp = Notification.where([
                                'sender_id = ? and receiver_id = ? and action = ? ', current_user.id, id, 'follow'
                              ])
    if temp.blank?
      notification = current_user.active_notifications.new(
        receiver_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :logged_in_user,
                only: %i[edit update destroy following followers]
  before_action :correct_user, only: %i[edit update]
  before_action :check_guest, only:  %i[destroy update]

  def index
    @cordinate = Cordinate.where(user_id: params[:user_id])
    @item = Item.where(user_id: params[:user_id])
    @users = User.all
    user_paginate
    cordinate_ransack_setup
    item_ransack_setup
  end

  def following
    @title = 'Following'
    @user = User.find(params[:id])
    @users = @user.following
    render 'show_follow'
  end

  def followers
    @title = 'Followers'
    @user = User.find(params[:id])
    @users = @user.followers
    render 'show_follow'
  end

  def blocking
    @title = 'blocking'
    @user = User.find(params[:id])
    @users = @user.blocking
    render 'show_follow'
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.account_activation(@user).deliver_now
      flash[:info] = 'Please check your email to activate your account.'
      redirect_to @user
    else
      redirect_to request.referer
    end
  end

  def destroy
    @user = User.find(params[:id])
    authorize! :delete, @user, message: 'ユーザーを削除する権限がありません。'
    @user.destroy
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = 'Profile updated'
      redirect_to @user
    else
      render 'edit'
    end
  end

  #  Cordinateのransackの設定------------

  def all_cordinate_season_search
    cordinate_season_ransack
  end

  def all_cordinate_tpo_search
    cordinate_tpo_ransack
  end

  def all_cordinate_rating_search
    cordinate_rating_ransack
  end

  def cordinate_ransack_setup
    cordinate_season_ransack
    cordinate_tpo_ransack
    all_cordinate_rating_search
  end

  def cordinate_season_ransack
    p_cordinate_season = Cordinate.ransack(params[:p_season],
                                           search_key: :p_season)
    @p_cordinate_season = p_cordinate_season.result
    @cordinate = Cordinate.where(user_id: current_user.id) if params[:p_season].blank?
  end

  def cordinate_tpo_ransack
    p_cordinate_tpo = Cordinate.ransack(params[:p_tpo], search_key: :p_tpo)
    @p_cordinate_tpo = p_cordinate_tpo.result
    @cordinate = Cordinate.where(user_id: current_user.id) if params[:p_tpo].blank?
  end

  def cordinate_rating_ransack
    p_cordinate_rating = Cordinate.ransack(params[:p_rating],
                                           search_key: :p_rating)
    @p_cordinate_rating = p_cordinate_rating.result
    @cordinate = Cordinate.where(user_id: current_user.id) if params[:p_rating].blank?
  end

  # Itemのransack設定------------

  def all_item_tpo_search
    item_tpo_ransack
  end

  def all_item_season_search
    item_season_ransack
  end

  def all_item_color_search
    item_color_ransack
  end

  def all_item_rating_search
    item_rating_ransack
  end

  def all_item_super_item_search
    item_super_item_ransack
  end

  def item_ransack_setup
    item_tpo_ransack
    item_rating_ransack
    item_season_ransack
    item_super_item_ransack
    item_color_ransack
  end

  def item_season_ransack
    q_item_season = Item.ransack(params[:q_season], search_key: :q_season)
    @q_item_season = q_item_season.result
    @item = Item.where(user_id: current_user.id) if params[:q_season].blank?
  end

  def item_tpo_ransack
    q_item_tpo = Item.ransack(params[:q_tpo], search_key: :q_tpo)
    @q_item_tpo = q_item_tpo.result
    @item = Item.where(user_id: current_user.id) if params[:q_tpo].blank?
  end

  def item_rating_ransack
    q_item_rating  = Item.ransack(params[:q_rating], search_key: :q_rating)
    @q_item_rating = q_item_rating.result
    @item = Item.where(user_id: current_user.id) if params[:q_rating].blank?
  end

  def item_color_ransack
    q_item_color = Item.ransack(params[:q_color], search_key: :q_color)
    @q_item_color = q_item_color.result
    @item = Item.where(user_id: current_user.id) if params[:q_color].blank?
  end

  def item_super_item_ransack
    q_item_super_item = Item.ransack(params[:q_super_item],
                                     search_key: :q_super_item)
    @q_item_super_item = q_item_super_item.result
    @item = Item.where(user_id: current_user.id) if params[:q_super_item].blank?
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :picture)
  end

  def sign_in(_user)
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end

  def owner_user
    @user = User.find(params[:id])
    @owner_user = user
    flash[:danger] = 'オーナーしか編集できません.' unless owner_user?(@user)
  end

  # 管理者かどうか確認
  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

  def check_guest
    if current_user.email == 'guest@example.com'
      redirect_to root_path,
                  alert: 'ゲストユーザーは削除や編集処理。'
    end
  end

  def user_paginate
    @users = User.all.page(params[:page])
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  # 引数で与えられたユーザーのGravatar画像を返す
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?d=identicon&?s=#{size}"
    # gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?d=spec/fixtures/fox.jpg&?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

app/views/users/_block.html.erb
<%= form_for(current_user.active_blocks.build, local: true) do |f| %>
<div><%= hidden_field_tag :blocked_id, @user.id %></div>
<%= f.submit "Block", class: "btn btn-outline-danger" %>
<% end %>

app/views/users/_block_form.html.erb
<% unless current_user?(@user) %>
<div id="block_form">
  <% if current_user.blocking?(@user) %>
  <%= render "unblock" %>
  <% else %>
  <%= render "block" %>
  <% end %>
</div>
<% end %>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
<div><%= hidden_field_tag :followed_id, @user.id %></div>
<%= f.submit "Follow", class: "btn btn-outline-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
<div id="follow_form">
  <% if current_user.following?(@user) %>
  <%= render "unfollow" %>
  <% else %>
  <%= render "follow" %>
  <% end %>
</div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
<%= f.label :名前 %>
<%= f.text_field :name, class: "form-control" %>

<%= f.label :メールアドレス %>
<%= f.email_field :email, class: "form-control" %>

<%= f.label :パスワード %>
<%= f.password_field :password, class: "form-control" %>

<%= f.label :パスワード確認, "Confirmation" %>
<%= f.password_field :password_confirmation, class: "form-control" %>

<i class="far fa-image fa-1x"></i><%= f.label :プロフ画像アップロード %>
<%= f.file_field :picture %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size / 196 / 257;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>
<%= f.submit "Save changes", class: "btn btn-primary" %>
<% end %>


<%# <a href="http://gravatar.com/emails" target="_blank">Change</a> %>

app/views/users/_unblock.html.erb
<%= form_for(current_user.active_blocks.find_by(blocked_id: @user.id),
             html: { method: :delete }, local: true) do |f| %>
<%= f.submit "Unblock", class: "btn btn-outline-info" %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
            html: { method: :delete }) do |f| %>
<%= f.submit "Unfollow", class: "btn btn-outline-warning" %>
<% end %>

app/views/users/edit.html.erb
<p class="profile">プロフィールの更新</p>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/users/index.html.erb
<p>すべてのユーザー</p>

<ul class="users">
  <% @users.each do |user| %>

  <div class="users_profile">
    <%= image_tag user.picture.url, size: 200 unless user.picture.blank? %>
    <li><%= link_to user.name, user %></li>
    <div class="stats">
      <a href="<%= following_user_path(user) %>">
        <strong id="following" class="stat">
          <%= user.following.count %>
        </strong>
        following
      </a>
      <a href="<%= followers_user_path(user) %>">
        <strong id="followers" class="stat">
          <%= user.followers.count %>
        </strong>
        followers
      </a>
    </div>

  </div>
  <% end %>
</ul>

app/views/users/new.html.erb
<div class="row login-form">
  <div class="col-10 col-md-offset-3 float-left">

    <%= form_for(@user, url: signup_path) do |f| %>
    <%= render "shared/error_messages" %>

    <%= f.label :名前 %>
    <%= f.text_field :name, class: "form-control" %>

    <%= f.label :メール %>
    <%= f.email_field :email, class: "form-control" %>


    <%= f.label :パスワード %>
    <%= f.password_field :password, class: "form-control" %>

    <%= f.label :確認用のパスワード, "確認" %>
    <%= f.password_field :password_confirmation, class: "form-control" %>


    <%= f.submit "新規アカウントを作成する", class: "btn btn-outline-secondary" %>
    <% end %>
  </div>
</div>

<p>アカウントを作成せずにログインする↓(下のどちらかのログイン方法を選択してください。)</p>
<%= link_to 'ゲストとしてログイン', guest_login_path, method: :post, class: "nav-link", data: {turbolinks: false}, class: "btn btn-outline-success"  %>
<%= link_to "ユーザーアカウントをお持ちの方", login_path, class: "nav-link", data: {turbolinks: false},  class: "btn btn-outline-primary" %>

app/views/users/show.html.erb
<h3>ユーザー詳細ページ</h3>
<section class="user_info">
  <%= image_tag @user.picture.url unless @user.picture.blank? %>
  <ul>
    <li> ユーザー名：<%= @user.name %></li>
    <li> 登録日時：<%= @user.created_at %></li>
  </ul>
</section>
<section class="stats">
  <%= render 'shared/stats' %>
</section>

<%= render 'follow_form' if logged_in? %>
<%= render  'block_form' if logged_in? %>

<% unless @current_user == nil  %>
<% if @current_user.admin  && !@current_user == @user %>
<li><%= link_to "delete" , @user, method: :delete, data: { confirm: "You sure?" } %></li>
<% end %>
<% end %>


<p class="p-profile">アイテム一覧</p>
<div class="row profile-items justify-content-center">
  <% @user.items.each do |item| %>
  <div class="item_each_images">
    <%= link_to image_tag( item.picture.url), item_show_path( user_id: item.user_id, id: item.id), size: "374.14x250", data: {turbolinks: false} unless item.picture.blank? %>
  </div>
  <% end %>
</div>

<p class="p-profile">コーデ一覧</p>
<div class="row profile-cordinates justify-content-center">
  <% @user.cordinates.each do |cordinate| %>
  <div class="cordinate_each_images">
    <%= link_to image_tag( cordinate.picture.url), cordinate_show_path( user_id: cordinate.user_id, id: cordinate.id), size: "374.14x250", data: {turbolinks: false}  unless cordinate.picture.blank? %>
  </div>
  <% end %>
</div>


<p class="p-profile">いいねしている投稿</p>
<div class="row profile-cordinates justify-content-center">
  <% @user.liked_cordinates.each do |cordinate| %>
  <div class="cordinate_each_images">
    <% @cordinate_for_picture = Cordinate.find(cordinate.id) %>
    <%= link_to image_tag(@cordinate_for_picture.picture.url), cordinate_show_path( user_id: @cordinate_for_picture.user_id, id:  @cordinate_for_picture.id), size: "374.14x250", data: {turbolinks: false} unless cordinate.picture.blank? %>
  </div>
  <% end %>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= image_tag @user.picture.url unless @user.picture.blank? %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user, data: {turbolinks: false} %></span>
    </section>
    <section class="stats">
      <%= render "shared/stats" %>

      <% if @users.any? %>
      <div class="user_avatars">
        <% @users.each do |user| %>
        <%= link_to image_tag(user.picture.url), user_show_path(user_id: user.id), size: 200, data: {turbolinks: false} unless user.picture.blank? %>
        <% end %>
      </div>
      <% end %>
    </section>
  </aside>


  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
    <ul class="users follow">
      <% #= render @users %>
    </ul>
    <% end %>
  </div>
</div>