config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'users#new'
  # root "/LP"
  get '/lp', to: redirect('/lp.html')

  resources :items
  resources :cordinates
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  resources :microposts, only: %i[create destroy]
  resources :relationships, only: %i[create destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  resources :relationships, only: %i[create destroy]
  resources :blocks, only: %i[create destroy]

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :users do
    member do
      get :blocking, :blockers
    end
  end

  delete '/logout', to: 'sessions#destroy'
  get 'search', to: 'items#search'
  get '/help', to: 'static_pages#help'
  get '/home', to: 'static_pages#home'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  # かんたんログインの実装
  post '/sessions/guest_log_in', to: 'sessions#guest_login', as: 'guest_login'
  # 全てのUserのItemとCordinateをみる
  get '/:user_id/cordinates/allusers', to: 'cordinates#all_cordinate_show',
                                       as: 'all_cordinate_show'
  get '/:user_id/items/allusers', to: 'items#all_item_show', as: 'all_item_show'

  # Rasnsackで全てのUserのItemをみる
  get '/:user_id/items/items_search/tpo', to: 'items#all_item_tpo_search',
                                          as: 'items_tpo_search'
  get '/:user_id/items/items_search/rating',
      to: 'items#all_item_rating_search', as: 'items_rating_search'
  get '/:user_id/items/items_search/season',
      to: 'items#all_item_season_search', as: 'items_serch_season'
  get '/:user_id/items/items_search/color', to: 'items#all_item_color_search',
                                            as: 'items_search_color'
  get '/:user_id/items/items_search/super_item',
      to: 'items#all_item_super_item_search', as: 'items_search_super_item'

  # Rasnsackで全てのUserのCordinateをみる
  get '/:user_id/cordinates/cordinates_search/tpo', to: 'cordinates#all_cordinate_tpo_search',
                                                    as: 'cordinates_tpo_search'
  get '/:user_id/cordinates/cordinates_search/season', to: 'cordinates#all_cordinate_season_search',
                                                       as: 'cordinates_season_search'
  get '/:user_id/cordinates/cordinates_search/rating', to: 'cordinates#all_cordinate_rating_search',
                                                       as: 'cordinates_rating_search'

  get '/:user_id/items/cordinates_search',
      to: 'cordinates#all_cordinate_search', as: 'cordinates_serch'

  # userコントローラー
  get '/users/:user_id/index', to: 'users#index', as: 'allusers_index'
  get '/users/new', to: 'users#new', as: 'user_new'
  get '/users/:id/', to: 'users#show', as: 'user_show'
  # get '/users/:id/ranking', to: 'users#ranking', as: 'user_ranking'

  # itemsコントローラー(個別User)
  get '/users/:user_id/items/all', to: 'items#user_all_item_show',
                                   as: 'user_item'
  get '/users/:user_id/items/new', to: 'items#new', as: 'item_new'
  get '/users/:user_id/items/:id', to: 'items#show', as: 'item_show'
  patch '/users/:user_id/items/:id/edit', to: 'items#update', as: 'item_update'
  get '/users/:user_id/items/:id/edit', to: 'items#edit', as: 'item_edit'
  get '/users/:user_id/cordinates/:cordinate_id/items',
      to: 'items#cordinate_show', as: 'cordinate_item_show'
  get '/users/:user_id/cordinates/:cordinate_id/items/search', to: 'items#cordinate_search_si',
                                                               as: 'cordinate_search_si'
  post '/users/:user_id/items/', to: 'items#create', as: 'item_create'
  delete '/users/:user_id/items/:id', to: 'items#destroy', as: 'item_delete'

  # cordinateコントローラー(個別のUser)
  get '/users/:user_id/cordinates/all',
      to: 'cordinates#user_all_cordinate_show', as: 'user_cordinate'
  get '/users/:user_id/cordinates/new', to: 'cordinates#new', as: 'cordinate_new'
  get '/users/:user_id/cordinates/:id', to: 'cordinates#show',
                                        as: 'cordinate_show'
  get '/users/:user_id/cordinates/:id/edit', to: 'cordinates#edit',
                                             as: 'cordinate_edit'
  post '/users/:user_id/cordinates/', to: 'cordinates#create',
                                      as: 'cordinate_create'

  # get '/users/:user_id/cordinates/:id/modal', to: 'cordinates#cordinate_modal',

  # saveに関してリファクタリングの可能性を検討する
  get '/users/:user_id/cordinates/:id/items/:item_id/edit',
      to: 'cordinates#item_edit', as: 'cordinate_item_edit'

  # controllerを変える必要はあるのか？
  patch '/users/:user_id/cordinates/:id/', to: 'cordinates#update',
                                           as: 'cordinate_patch'
  delete '/users/:user_id/cordinates/:id', to: 'cordinates#destroy',
                                           as: 'cordinate_delete'
  patch '/users/:user_id/cordinates/:id/items/:item_id',
        to: 'cordinates#item_update', as: 'items_patch'

  # Commentシリーズ(個別のUser)
  post '/users/:user_id/cordinates/:id/comments', to: 'comments#create',
                                                  as: 'comment_create'
  delete '/users/:user_id/cordinates/:id/comments/:comment_id',
         to: 'comments#destroy', as: 'comment_delete'

  # Likecordinateシリーズ(個別のUser)
  post '/users/:user_id/cordinates/:id/likecordinates',
       to: 'likecordinates#create', as: 'likecordinate_create'
  delete '/users/:user_id/cordinates/:id/likecordinates/:likecordinate_id', to: 'likecordinates#destroy',
                                                                            as: 'likecordinate_delete'
  # Notificationsコントローラー(個別のUser)
  get '/users/:user_id/notifications/', to: 'notifications#index',
                                        as: 'notifications'
  delete '/users/notifications/alldelete', to: 'notifications#destroy_all',
                                           as: 'destroy_all_users_notifications'
end

app/views/shared/_cordinate_comment.erb
<% unless @cordinate.user.id === current_user.id %>
                      <div class = "cordinate_comments">
                      <i class="fas fa-user-edit fa-1x"></i>コーデへのコメント
                      <%= form_for(@comment, url: {controller: 'comments' , action: 'create' }, method: :post) do |i| %>
                        <%= i.text_field :comment %>
                          <br>
                          <%= i.submit 'コメントする' %>
                            <% end %>
                                 <% end %>
                            
  <p>投稿詳細ページ</p>
              <p><i class="far fa-comment fa-1x"></i>コメント一覧</p>
        <% if @cordinate.commented_users && @comment !=nil %>                                                   
<% @comments.each do |c| %>

<div class= "cordinate_responses">
                              <div class= "cordinate_responses">                                                           
                                <%= link_to image_tag( c.user.picture.url), user_show_path(id:  c.user.id ), size: 150, data: {turbolinks: false} unless @comment.user.picture.blank? %>                         
                              <%=link_to c.user.name, user_show_path(id: c.user.id )%>から
                             <br>                                       
                         <div class = "comment_box">
 <li><%= c.comment %></li>                                                                                    
 </div>                                                                               
                              </div>

  <% if  c.user.id  === current_user.id %>
                              <li><%= button_to "コメントを取り消す" , comment_delete_path( user_id:  c.user.id , comment_id: c.id, id: @cordinate.id ),
                                :controller=>"comments", :action=> "destroy", :method => "delete", class: "comment_like_btn" %></li>
                                <% end %>

  </div>
                                               
      <% end %>
      <% end %>

app/views/shared/_cordinate_item_images_edit.erb
       <div class=" d-flex images float-left col-sm-12 flex-grow  ">
              <div class=" flex-fill flex-row">
                     <div class=" flex-fill cordeimg float-left">
                            <% if @si_tops %>
                            <%= image_tag @si_tops, data:{ image: 'img1'}, size: "250x250", class: "pic" %>
                            <div class=" image-text">
                                   トップス登録済
                                     <%= link_to '選びなおす',"/users/#{params[:user_id]}/cordinates/#{params[:id]}/items/search?q[super_item_eq]=1", class: "images", data: {turbolinks: false} %>
                            </div>
                            <% else %>
                                <%= link_to image_tag("logo-tops.png", size: "215x257"), "/users/#{params[:user_id]}/cordinates/#{params[:id]}/items/search?q[super_item_eq]=1",class: "images", data: {turbolinks: false} %>
                            <div class="image-text">
                                 <%= link_to 'トップス選ぶ', "/users/#{params[:user_id]}/cordinates/#{params[:id]}/items/search?q[super_item_eq]=1",class: "images", data: {turbolinks: false} %>
                            </div>
                            <% end %>
                     </div>


  

                     <div class="flex-fill cordeimg float-left">
                            <% if @si_bottoms %>
                            <%= image_tag @si_bottoms, data:{ image: 'img2'}, size: "250x257", class: "pic"  %>
                            <div class="image-text">
                                   ボトムス登録済
                                   <%= link_to '選びなおす',"/users/#{params[:user_id]}/cordinates/#{params[:id]}/items/search?q[super_item_eq]=2", class: "images", data: {turbolinks: false} %>
                            </div>
                            <% else %>                            
   <%= link_to image_tag( "logo-pants.png",
   size: "215x257"), "/users/#{params[:user_id]}/cordinates/#{params[:id]}/items/search?q[super_item_eq]=2",class: "images", data: {turbolinks: false} %>
                            <div class="image-text">
                                   <%= link_to 'ボトムス選ぶ',"/users/#{params[:user_id]}/cordinates/#{params[:id]}/items/search?q[super_item_eq]=2",data: {turbolinks: false} , class: "images", data: {turbolinks: false} %>
                            </div>
                            <% end %>
                     </div>
                     <div class="flex-fill cordeimg float-left">
                            <% if @si_shoes %>
                            <%= image_tag @si_shoes, data:{ image: 'img3'}, size: "250x240", class: "pic"  %>
                            <div class="image-text align-items-center">
                                   シューズ登録済
                                     <%= link_to '選びなおす',"/users/#{params[:user_id]}/cordinates/#{params[:id]}/items/search?q[super_item_eq]=3", class: "images", data: {turbolinks: false} %>
                            </div>
                            <% else %>                            
                               <%= link_to image_tag("logo-shoes.png", size: "215x257"), "/users/#{params[:user_id]}/cordinates/#{params[:id]}/items/search?q[super_item_eq]=3",class: "images", data: {turbolinks: false} %>
                            <div class="image-text ">
                                   <%= link_to 'シューズを選ぶ',  "/users/#{params[:user_id]}/cordinates/#{params[:id]}/items/search?q[super_item_eq]=3", data: {turbolinks: false} , class: "images" %>
                            </div>
                            <% end %>
                     </div>
                     <div class="flex-fill cordeimg  float-left">
                            <% if @si_outer %>
                            <%= image_tag @si_outer, data:{ image: 'img4'}, size: "250x240", class: "pic"  %>
                            <div class="image-text">
                            アウター登録済
                              <%= link_to '選びなおす',"/users/#{params[:user_id]}/cordinates/#{params[:id]}/items/search?q[super_item_eq]=0", class: "images", data: {turbolinks: false} %>
                            </div>
                            <% else %>
                            <div class= "outer-image">
    <%= link_to image_tag("outer.png", size: "215x257"), "/users/#{params[:user_id]}/cordinates/#{params[:id]}/items/search?q[super_item_eq]=0",class: "images", data: {turbolinks: false} %>
    </div>
                            <div class="image-text ">

                            <div class="image-text">
                                   <%= link_to 'アウターを選ぶ',  "/users/#{params[:user_id]}/cordinates/#{params[:id]}/items/search?q[super_item_eq]=0", data: {turbolinks: false} , class: "images"%>
                            </div>
                            <% end %>
                     </div>
              </div>
       </div>
<script>
var cordeimgs = document.querySelectorAll('.pic');
for(var i = 0; i < cordeimgs.length; i++) {
  cordeimgs[i].onclick = function() {
    var src = this.getAttribute('src');
    document.getElementById('bigimg').src = src ;
  };
}
</script>

app/views/shared/_cordinate_like.erb
           <% if @cordinate.liked_users && @likecordinates !=nil %>
                          <p><i class="far fa-thumbs-up fa-1x"></i>いいね:合計<%= @likecordinates_count %></p>
                          <% unless @cordinate.liked_users.nil? %>
                            <% @cordinate.liked_users.each do |user| %>
                            <div class= "cordinate_responses">
                              <div class= "cordinate_responses">                             
                               <%= link_to image_tag(user.picture.url), user_show_path(id: user.id ), size: 150, data: {turbolinks: false} unless user.picture.blank? %>
                              <%= @user.name %>へ</li>
                             <br>
                             <div class = "comment_box">
                              <li><%=link_to user.name, user_show_path(id: user.id )%>さんがいいねしました!</li>
                              </div>
                              <br>
                                <% if user.id === current_user.id %>
                              <li><%= button_to "いいねを取り消す" , likecordinate_delete_path( user_id: user.id, likecordinate_id: user.likecordinates, id: @cordinate.id ),
                                :controller=>"likecordinates", :action=> "destroy", :method => "delete", class: "comment_like_btn" %></li>
                                <% end %>
                                </div>
                              <% end %>
                                <% end %>
                                  <% end %>

app/views/shared/_item_color_select.erb
<% if request.path.include?("/new") %>
<%= form_for(@item, url: item_create_path) do |i| %>
<% end %>
 <% else %>
<%= form_for(@item, url:edit_user_item_path) do |i| %>
<% end %>


 <div class="field">

                   <span class="color_select">カラー選択</span><br>
                   <div class="radio-inline">

                    <div class = "color_list">

 <li>
                          <div class="color-black">
                            <%= i.radio_button :color, :ブラック, checked: "checked" %>
                              <%= i.label :ブラック, class: "color_label" %>
                                <a></a>
                          </div>
                        </li>
                        <li>
                          <div class="color-white">
                            <%= i.radio_button :color, :ホワイト, checked: "checked" %>
                              <%= i.label :ホワイト, class: "color_label" %>
                                <a></a>
                          </div>
                        </li>
                        <li>
                          <div class="color-gray">
                            <%= i.radio_button :color, :グレー, checked: "checked" %>
                              <%= i.label :グレー, class: "color_label" %>
                                <a></a>
                          </div>
                        </li>
                        <li>
                          <div class="color-red">
                            <%= i.radio_button :color, :レッド, checked: "checked" %>
                              <%= i.label :レッド, class: "color_label" %>
                                <a></a>
                          </div>
                        </li>
                        <li>
                          <div class="color-navy">
                            <%= i.radio_button :color, :ネイビー, checked: "checked" %>
                              <%= i.label :ネイビー, class: "color_label" %>
                                <a></a>
                          </div>
                        </li>
                        <li>
                          <div class="color-lightblue">
                            <%= i.radio_button :color, :ライトブルー, checked: "checked" %>
                              <%= i.label :ライトブルー, class: "color_label" %>
                                <a></a>
                          </div>
                        </li>
                        <li>
                          <div class="color-yellow">
                            <%= i.radio_button :color, :イエロー, checked: "checked" %>
                              <%= i.label :イエロー, class: "color_label" %>
                                <a></a>
                          </div>
                        </li>
                        <li>
                          <div class="color-green">
                            <%= i.radio_button :color, :グリーン, checked: "checked" %>
                              <%= i.label :グリーン, class: "color_label" %>
                                <a></a>
                          </div>
                        </li>



                        <li>
                          <div class="color-orenge">
                            <%= i.radio_button :color, :オレンジ, checked: "checked" %>
                              <%= i.label :オレンジ, class: "color_label" %>
                                <a></a>
                          </div>
                        </li>
                        <li>
                          <div class="color-olive">
                            <%= i.radio_button :color, :オリーブ, checked: "checked" %>
                              <%= i.label :オリーブ, class: "color_label" %>
                                <a></a>
                          </div>
                        </li>
                        <li>
                          <div class="color-neon">
                            <%= i.radio_button :color, :ネオン, checked: "neon" %>
                              <%= i.label :ネオン, class: "color_label" %>
                                <a></a>
                          </div>
                        </li>
                        <li>
                          <div class="color-border">
                            <%= i.radio_button :color, :ボーダー, checked: "checked" %>
                              <%= i.label :ボーダー, class: "color_label" %>
                                <a></a>
                          </div>
                        </li>
                        <li>
                          <div class="color-patternned">
                            <%= i.radio_button :color, :水たま, checked: "checked" %>
                              <%= i.label :水たま, class: "color_label" %>
                                <a></a>
                          </div>
                        </li>
                        <li>
                          <div class="color-denim">
                            <%= i.radio_button :color, :デニム, checked: "checked" %>
                              <%= i.label :デニム, class: "color_label" %>
                                <a></a>
                          </div>
                        </li>
                        <li>
                          <div class="color-others">
                            <%= i.radio_button :color, :他のカラー, checked: "checked" %>
                              <%= i.label :他のカラー, class: "color_label" %>
                                <a></a>
                          </div>
                        </li>


                    </div>
                 </div>

<% end %>

app/views/shared/_item_data_setting.erb
  <%= i.label :season, "季節:" %><i class="fa fa-leaf" aria-hidden="true"></i>
                    <%= i.select :season, Item.seasons.keys %>

                    <%= i.label :tpo, "TPO:" %>
                    <%= i.select :tpo, Item.tpos.keys %>

                    <%= i.label :super_item, "カテゴリー：" %>
                    <%= i.select :super_item, Item.super_items.keys %>

                    <%= i.label :content, "内容" %>
                    <%= i.select :content, Item.contents.keys %>

                    <%= i.label :rating,'評価ID：' %>
                    <%= i.select :rating, Item.ratings.keys %>
               
                  <%= i.label :memo, "メモ" %><i class="far fa-edit fa-1x"></i><i class="far fa-edit fa-1x"></i>
                  <%= i.text_field :memo %>

               <div class="form-group row" id="star">
                 <%= i.label :rating,'評価ID：' %>
                 <%= i.hidden_field :rating, id: :review_star, disable_after_rate: false  %>
               </div>

app/views/shared/_modal.html.erb
<div data-controller="confirm-delete" data-confirm-delete-target="modal" class="fixed inset-0 flex items-center justify-center bg-gray-800 bg-opacity-75 hidden">
  <div class="bg-white rounded-lg shadow-lg p-6 relative">
    <button data-action="click->confirm-delete#cancel" class="absolute top-2 right-2 text-gray-500 hover:text-gray-700">&times;</button>
    <h2 class="text-xl font-bold mb-4">Confirm Delete</h2>
    <p class="mb-4">本当に削除してもよろしいですか？</p>
    <div class="flex justify-end space-x-2">
      <button data-action="click->confirm-delete#cancel" class="px-4 py-2 bg-gray-500 text-white rounded hover:bg-gray-600">Cancel</button>
      <button data-action="click->confirm-delete#proceed" class="px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600">OK</button>
    </div>
  </div>
</div> 

app/views/shared/_navbar.html.erb
  <nav class="bg-gray-800">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="flex items-center justify-between h-16">
        <div class="flex items-center">
          <a href="<%= root_path %>" class="text-white text-xl font-bold">スピウェア</a>
          <div class="hidden md:block">
            <div class="ml-10 flex items-baseline space-x-4">
              <%= link_to 'ホーム', root_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
              <%= link_to 'アイテム', items_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
              <%= link_to 'コーデ', cordinates_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
              <%= link_to 'ユーザー', users_path, class: "text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" %>
            </div>
          </div>
        </div>
        <div class="flex items-center space-x-4">
          <% if current_user %>
            <span class="text-gray-300 text-sm">ようこそ, <%= current_user.name %> さん</span>
            <%= link_to 'ログアウト', logout_path, method: :delete, class: "bg-red-500 hover:bg-red-700 text-white px-3 py-2 rounded-md text-sm font-medium" %>
          <% else %>
            <%= link_to 'ログイン', login_path, class: "bg-blue-500 hover:bg-blue-700 text-white px-3 py-2 rounded-md text-sm font-medium" %>
          <% end %>
        </div>
      </div>
    </div>
  </nav> 

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>

  <% if @user == current_user %>
  <a href="<%= blocking_user_path(@user) %>">
    <strong id="blocking" class="stat">
      <%= @user.blocking.count unless @user %>
    </strong>
    blocks
  </a>
</div>
<% end %>

app/views/shared/_whether_report.html.erb
<div class="weather-body">
<div class="weather">
      <ul class="week">
        <li class="day">
          <div class="day-of-the-week">きょう</div>
          <div class="weather-icon">
           <span><div id="icon0"></div></span>
          </div>
          <div class="temperature">
              <div id="temp0"></div>
          </div>
        </li>
        <li class="day">
          <div class="day-of-the-week">あした</div>
          <div class="weather-icon">
               <div id="icon1"></div>
          </div>
          <div class="temperature">
            <div id="temp1"></div>
          </div>
        </li>
        <li class="day">
          <div class="day-of-the-week">あさって</div>
          <div class="weather-icon">
             <div id="icon2"></div>
          </div>
          <div class="temperature">
            <div id="temp2"></div>
          </div>
        </li>
        <li class="day">
          <div class="day-of-the-week">3日ご</div>
          <div class="weather-icon">
               <div id="icon3"></div>
          </div>
          <div class="temperature">
            <div id="temp3"></div>
          </div>
        </li>
      </ul>
    </div>
 </div>