config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'users#new'
  # root "/LP"
  get '/lp', to: redirect('/lp.html')

  resources :items
  resources :cordinates
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  resources :microposts, only: %i[create destroy]
  resources :relationships, only: %i[create destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  resources :relationships, only: %i[create destroy]
  resources :blocks, only: %i[create destroy]

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :users do
    member do
      get :blocking, :blockers
    end
  end

  delete '/logout', to: 'sessions#destroy'
  get 'search', to: 'items#search'
  get '/help', to: 'static_pages#help'
  get '/home', to: 'static_pages#home'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  # かんたんログインの実装
  post '/sessions/guest_log_in', to: 'sessions#guest_login', as: 'guest_login'
  # 全てのUserのItemとCordinateをみる
  get '/:user_id/cordinates/allusers', to: 'cordinates#all_cordinate_show',
                                       as: 'all_cordinate_show'
  get '/:user_id/items/allusers', to: 'items#all_item_show', as: 'all_item_show'

  # Rasnsackで全てのUserのItemをみる
  get '/:user_id/items/items_search/tpo', to: 'items#all_item_tpo_search',
                                          as: 'items_tpo_search'
  get '/:user_id/items/items_search/rating',
      to: 'items#all_item_rating_search', as: 'items_rating_search'
  get '/:user_id/items/items_search/season',
      to: 'items#all_item_season_search', as: 'items_serch_season'
  get '/:user_id/items/items_search/color', to: 'items#all_item_color_search',
                                            as: 'items_search_color'
  get '/:user_id/items/items_search/super_item',
      to: 'items#all_item_super_item_search', as: 'items_search_super_item'

  # Rasnsackで全てのUserのCordinateをみる
  get '/:user_id/cordinates/cordinates_search/tpo', to: 'cordinates#all_cordinate_tpo_search',
                                                    as: 'cordinates_tpo_search'
  get '/:user_id/cordinates/cordinates_search/season', to: 'cordinates#all_cordinate_season_search',
                                                       as: 'cordinates_season_search'
  get '/:user_id/cordinates/cordinates_search/rating', to: 'cordinates#all_cordinate_rating_search',
                                                       as: 'cordinates_rating_search'

  get '/:user_id/items/cordinates_search',
      to: 'cordinates#all_cordinate_search', as: 'cordinates_serch'

  # userコントローラー
  get '/users/:user_id/index', to: 'users#index', as: 'allusers_index'
  get '/users/new', to: 'users#new', as: 'user_new'
  get '/users/:id/', to: 'users#show', as: 'user_show'
  # get '/users/:id/ranking', to: 'users#ranking', as: 'user_ranking'

  # itemsコントローラー(個別User)
  get '/users/:user_id/items/all', to: 'items#user_all_item_show',
                                   as: 'user_item'
  get '/users/:user_id/items/new', to: 'items#new', as: 'item_new'
  get '/users/:user_id/items/:id', to: 'items#show', as: 'item_show'
  patch '/users/:user_id/items/:id/edit', to: 'items#update', as: 'item_update'
  get '/users/:user_id/items/:id/edit', to: 'items#edit', as: 'item_edit'
  get '/users/:user_id/cordinates/:cordinate_id/items',
      to: 'items#cordinate_show', as: 'cordinate_item_show'
  get '/users/:user_id/cordinates/:cordinate_id/items/search', to: 'items#cordinate_search_si',
                                                               as: 'cordinate_search_si'
  post '/users/:user_id/items/', to: 'items#create', as: 'item_create'
  delete '/users/:user_id/items/:id', to: 'items#destroy', as: 'item_delete'

  # cordinateコントローラー(個別のUser)
  get '/users/:user_id/cordinates/all',
      to: 'cordinates#user_all_cordinate_show', as: 'user_cordinate'
  get '/users/:user_id/cordinates/new', to: 'cordinates#new', as: 'cordinate_new'
  get '/users/:user_id/cordinates/:id', to: 'cordinates#show',
                                        as: 'cordinate_show'
  get '/users/:user_id/cordinates/:id/edit', to: 'cordinates#edit',
                                             as: 'cordinate_edit'
  post '/users/:user_id/cordinates/', to: 'cordinates#create',
                                      as: 'cordinate_create'

  # get '/users/:user_id/cordinates/:id/modal', to: 'cordinates#cordinate_modal',

  # saveに関してリファクタリングの可能性を検討する
  get '/users/:user_id/cordinates/:id/items/:item_id/edit',
      to: 'cordinates#item_edit', as: 'cordinate_item_edit'

  # controllerを変える必要はあるのか？
  patch '/users/:user_id/cordinates/:id/', to: 'cordinates#update',
                                           as: 'cordinate_patch'
  delete '/users/:user_id/cordinates/:id', to: 'cordinates#destroy',
                                           as: 'cordinate_delete'
  patch '/users/:user_id/cordinates/:id/items/:item_id',
        to: 'cordinates#item_update', as: 'items_patch'

  # Commentシリーズ(個別のUser)
  post '/users/:user_id/cordinates/:id/comments', to: 'comments#create',
                                                  as: 'comment_create'
  delete '/users/:user_id/cordinates/:id/comments/:comment_id',
         to: 'comments#destroy', as: 'comment_delete'

  # Likecordinateシリーズ(個別のUser)
  post '/users/:user_id/cordinates/:id/likecordinates',
       to: 'likecordinates#create', as: 'likecordinate_create'
  delete '/users/:user_id/cordinates/:id/likecordinates/:likecordinate_id', to: 'likecordinates#destroy',
                                                                            as: 'likecordinate_delete'
  # Notificationsコントローラー(個別のUser)
  get '/users/:user_id/notifications/', to: 'notifications#index',
                                        as: 'notifications'
  delete '/users/notifications/alldelete', to: 'notifications#destroy_all',
                                           as: 'destroy_all_users_notifications'
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  belongs_to :user
  belongs_to :cordinate, optional: true
  validates :super_item, presence: true
  validates :season, presence: true
  validates :tpo, presence: true
  validates :color, presence: true
  validates :content, presence: true
  validates :memo, length: { maximum: 140 }
  validate :picture_size

  mount_uploader :picture, PictureUploader

  enum super_item: %w[アウター トップス ボトムス シューズ]
  enum season: %w[春 夏 秋 冬]
  enum tpo: %w[デート リラックス♪ スポーツ おでかけ 仕事]
  enum rating: %w[1 2 3 4 5]
  enum content: %w[Tシャツ シャツ ポロシャツ パーカー スウェット セーター パンツ デニムパンツ ジャケット コート スニーカー
                   ローファー 革靴 ブーツ ビジネス その他]
  enum color: %w[ブラック ホワイト グレー レッド ネイビー ライトブルー イエロー グリーン オレンジ オリーブ ネオン ボーダー 水たま
                 デニム 他のカラー]

  # Itemのseasonカラムにそれぞれの季節を入れるメソッドを定義する
  def self.spring
    Item.where(season: :春)
  end

  def self.summer
    Item.where(season: :夏)
  end

  def self.winter
    Item.where(season: :冬)
  end

  def self.autmun
    Item.where(season: :秋)
  end

  # ItemのtpoカラムにそれぞれのTPOを入れるメソッドを定義する
  def self.dating
    @item = Item.where(tpo: :デート)
  end

  def self.relax
    Item.where(tpo: :リラックス♪)
  end

  def self.sports
    Item.where(tpo: :スポーツ)
  end

  def self.town
    Item.where(tpo: :おでかけ)
  end

  # Itemのsuperitemカラムにそれぞれのsuper_itemを入れるメソッドを定義する
  def self.tops
    Item.where(super_item: :トップス)
  end

  def self.bottoms
    Item.where(super_item: :ボトムス)
  end

  def self.shoes
    Item.where(super_item: :シューズ)
  end

  def self.outer
    Item.where(super_item: :アウター)
  end

  private

  # アップロードされた画像のサイズをバリデーションする
  def picture_size
    errors.add(:picture, 'should be less than 5MB') if picture.size > 5.megabytes
  end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  before_action :logged_in_user, only: %i[create edit delete update]
  before_action :blocking?, only: %i[show]

  def index
    item_paginate
    @cordinate = Cordinate.where(user_id: params[:user_id])
    item_cordinate_ransack_setup
  end

  def all_item_show
    item_paginate
    item_cordinate_ransack_setup
  end

  def user_all_item_show
    @items = Item.where(user_id: params[:user_id]).page(params[:page])
    item_cordinate_ransack_setup
  end

  def new
    @item = Item.new
    @item.user_id = current_user.id
    authorize! :create, @item, message: '他人のアイテムを作成する権限がありません。'
    @item.user_id = params[:user_id]
  end

  def create
    @item = Item.new(item_params)
    @item.user_id = params[:user_id]
    unless params[:picture].nil?
      img = MiniMagick::Image.read(params[:picture])
      img.resize_to_fill '169x225'
    end

    @item.save
    flash[:success] = 'Itemを作成しました!'
    redirect_to item_show_path(user_id: @item.user.id, id: @item.id)
  end

  def show
    @item = Item.find(params[:id])
    cordinate_ransack_setup
  end

  def item_show
    @item = Item.find(params[:user_id])
    item_ransack_setup
    cordinate_ransack_setup F
  end

  def cordinate_show
    @item = Item.find_by(id: params[:id])
    @cordinate = Cordinate.find(params[:cordinate_id])
  end

  def edit
    @item = Item.find(params[:id])
    authorize! :update, @item, message: '他人のアイテムを編集する権限がありません。'
    @item.picture.cache! unless @item.picture.blank?
  end

  def update
    @item = Item.find(params[:id])
    if @item.update_attributes(item_params)
      flash[:success] = '更新しました!!'
      redirect_to item_show_path(user_id: params[:user_id], id: @item.id)
    else
      redirect_to request.referer
    end
  end

  def destroy
    @item = Item.find(params[:id])
    authorize! :delete, @item, message: '他人のアイテムを削除する権限がありません。'
    redirect_to request.referer if cannot? :destroy, @item
    @item.destroy
    flash[:success] = 'アイテムを削除しました!!'
    redirect_to user_item_path(user_id: @item.user.id)
  end

  def cordinate_search_si
    q_cordinate = Item.ransack(params[:q])
    # @items = Item.find(params[:user_id])
    case params[:q]
    when { 'super_item_eq' => '0' }
      @item = Item.where(user_id: params[:user_id], super_item: 0)
    when { 'super_item_eq' => '1' }
      @item = Item.where(user_id: params[:user_id], super_item: 1)
    when { 'super_item_eq' => '2' }
      @item = Item.where(user_id: params[:user_id], super_item: 2)
    when { 'super_item_eq' => '3' }
      @item = Item.where(user_id: params[:user_id], super_item: 3)
    end
  end

  # ransackの設定------------------------

  def item_cordinate_ransack_setup
    item_ransack_setup
    cordinate_ransack_setup
  end

  def item_ransack_setup
    item_tpo_ransack
    item_rating_ransack
    item_season_ransack
    item_super_item_ransack
    item_color_ransack
  end

  def cordinate_ransack_setup
    cordinate_season_ransack
    cordinate_tpo_ransack
    cordinate_rating_ransack
    # all_cordinate_rating_search
  end

  #  Cordinateのransackの設定--------------

  def all_cordinate_season_search
    cordinate_season_ransack
  end

  def all_cordinate_tpo_search
    cordinate_tpo_ransack
  end

  def all_cordinate_rating_search
    cordinate_rating_ransack
  end

  def cordinate_season_ransack
    p_cordinate_season = Cordinate.ransack(params[:p_season],
                                           search_key: :p_season)
    @p_cordinate_season = p_cordinate_season.result
    @cordinate = Cordinate.where(user_id: params[:user_id]) if params[:p_season].blank?
  end

  def cordinate_tpo_ransack
    p_cordinate_tpo = Cordinate.ransack(params[:p_tpo], search_key: :p_tpo)
    @p_cordinate_tpo = p_cordinate_tpo.result
    @cordinate = Cordinate.where(user_id: params[:user_id]) if params[:p_tpo].blank?
  end

  def cordinate_rating_ransack
    p_cordinate_rating = Cordinate.ransack(params[:p_rating],
                                           search_key: :p_rating)
    @p_cordinate_rating = p_cordinate_rating.result
    @cordinate = Cordinate.where(user_id: params[:user_id]) if params[:p_rating].blank?
  end

  # Itemのransack設定--------------

  def all_item_tpo_search
    item_tpo_ransack
    item_cordinate_ransack_setup
  end

  def all_item_season_search
    item_season_ransack
    item_cordinate_ransack_setup
  end

  def all_item_color_search
    item_color_ransack
    item_cordinate_ransack_setup
  end

  def all_item_rating_search
    item_rating_ransack
    item_cordinate_ransack_setup
  end

  def all_item_super_item_search
    item_super_item_ransack
    item_cordinate_ransack_setup
  end

  def item_season_ransack
    q_item_season = Item.ransack(params[:q_season], search_key: :q_season)
    @q_item_season = q_item_season.result
    @item = Item.where(user_id: params[:user_id]) if params[:q_season].blank?
  end

  def item_tpo_ransack
    q_item_tpo = Item.ransack(params[:q_tpo], search_key: :q_tpo)
    @q_item_tpo = q_item_tpo.result
    @item = Item.where(user_id: params[:user_id]) if params[:q_tpo].blank?
  end

  def item_rating_ransack
    q_item_rating  = Item.ransack(params[:q_rating], search_key: :q_rating)
    @q_item_rating = q_item_rating.result
    @item = Item.where(user_id: params[:user_id]) if params[:q_rating].blank?
  end

  def item_color_ransack
    q_item_color = Item.ransack(params[:q_color], search_key: :q_color)
    @q_item_color = q_item_color.result
    @item = Item.where(user_id: params[:user_id]) if params[:q_color].blank?
  end

  def item_super_item_ransack
    q_item_super_item = Item.ransack(params[:q_super_item],
                                     search_key: :q_super_item)
    @q_item_super_item = q_item_super_item.result
    @item = Item.where(user_id: params[:user_id]) if params[:q_super_item].blank?
  end

  # Itemのransack設定------------

  def item_paginate
    @items = Item.all.page(params[:page])
  end

  private

  def item_params
    params.require(:item).permit(:id, :user_id, :super_item, :season, :tpo, :storage, :rating, :color, :memo,
                                 :picture, :content)
  end
end

app/views/items/_search_form.html.erb
  <%= search_form_for @q do |f| %>
      <br>
      <%= f.label :服のカテゴリー %>
      <%= f.radio_button :super_item_eq, '', {:checked => true} %>指定なし
      <%= f.radio_button :super_item_eq, 0 %>アウター
      <%= f.radio_button :super_item_eq, 1 %>トップス
      <%= f.radio_button :super_item_eq, 2 %>ボトムス
      <%= f.radio_button :super_item_eq, 3 %>シューズ
      <br>
      <%= f.label :season %>
      <%= f.radio_button :season_eq, '', {:checked => true} %>指定なし
      <%= f.radio_button :season_eq, 0 %>春
      <%= f.radio_button :season_eq, 1 %>夏
      <%= f.radio_button :season_eq, 2 %>秋
      <%= f.radio_button :season_eq, 3 %>冬
      <br>
      <%= f.label :TPO %>
      <%= f.radio_button :tpo_eq, '', {:checked => true} %>指定なし
      <%= f.radio_button :tpo_eq, 0 %>デート
      <%= f.radio_button :tpo_eq, 1 %>リラックス
      <%= f.radio_button :tpo_eq, 2 %>スポーツ
      <%= f.radio_button :tpo_eq, 3 %>街あそび
      <%= f.radio_button :tpo_eq, 4 %>仕事
  <%= f.submit "検索" %>
<% end %>

app/views/items/all_item_color_search.html.erb
<% @q_item_color.each do |item| %>
<div class="item_each_images ">
  <% if item.picture?  %>
  <%= link_to image_tag( item.picture.url), item_show_path( user_id: item.user_id, id: item.id), size: "374.14x250", data: {turbolinks: false} %>
  <% else %>
  <%= link_to image_tag('default_cordinate.png'), item_show_path( user_id: item.user_id, id: item.id), size: "374.14x250", data: {turbolinks: false}  %>
  <% end %>
  <div class="items_each_lists">
    <ul>
      <li>ID: <%= item.id %></li>
      <li>ユーザー：<%= link_to item.user.name , user_show_path( id: item.user.id), data: {turbolinks: false} %></li>
      <li>内容: <%= item.content %></li>
      <li>TPO: <%= item.tpo %></li>
      <li><i class="fa fa-leaf" aria-hidden="true"></i>季節: <%= item.season %></li>
      <li><i class="fa fa-trophy" aria-hidden="true"></i>評価：<span id="star-rate-<%= item.rating %>-<%= item.rating %>"></span>
      <li><i class="fa fa-trophy" aria-hidden="true"></i>評価:<span class="star5_rating" data-rate=<%= item.rating %>></span></li>
      <% unless item.cordinate_id.blank? %>
      <li><%= link_to "アイテムのコーデ" , cordinate_show_path( user_id: item.user_id, id: item.cordinate_id ), data: {turbolinks: false} %></li>
      <% else %>
      <li>コーデなしです </li>
      <% end %>
    </uL>
  </div>
</div>
<% end %>

app/views/items/all_item_rating_search.html.erb
<% @q_item_rating.each do |item| %>
<div class="item_each_images ">
  <% if item.picture?  %>
  <%= link_to image_tag( item.picture.url), item_show_path( user_id: item.user_id, id: item.id), size: "374.14x250", data: {turbolinks: false} %>
  <% else %>
  <%= link_to image_tag('default_cordinate.png'), item_show_path( user_id: item.user_id, id: item.id), size: "374.14x250", data: {turbolinks: false}  %>
  <% end %>
  <div class="items_each_lists">
    <ul>
      <li>ID: <%= item.id %></li>
      <li>ユーザー：<%= link_to item.user.name , user_show_path( id: item.user.id) %></li>
      <li>内容: <%= item.content %></li>
      <li>TPO: <%= item.tpo %></li>
      <li><i class="fa fa-leaf" aria-hidden="true"></i>季節: <%= item.season %></li>
      <li><i class="fa fa-trophy" aria-hidden="true"></i>評価:<span class="star5_rating" data-rate=<%= item.rating %>></span></li>
      <% unless item.cordinate_id.blank? %>
      <li><%= link_to "アイテムのコーデ" , cordinate_show_path( user_id: item.user_id, id: item.cordinate_id ), data: {turbolinks: false} %></li>
      <% else %>
      <li>コーデなしです </li>
      <% end %>
    </uL>
  </div>
</div>
<% end %>
</div>

app/views/items/all_item_show.html.erb
<% @items.each do |item| %>

<div class="item_each_images ">
  <% if item.picture?  %>
  <%= link_to image_tag( item.picture.url), item_show_path( user_id: item.user_id, id: item.id), size: "374.14x250", data: {turbolinks: false} unless item.picture.blank? %>
  <% else %>
  <%= link_to image_tag('default_cordinate.png'), item_show_path( user_id: item.user_id, id: item.id), size: "374.14x250", data: {turbolinks: false}  %>
  <% end %>

  <div class="items_each_lists">
    <ul>
      <li>ID: <%= item.id %></li>
      <li>ユーザー：<%= link_to item.user.name , user_show_path( id: item.user.id), data: {turbolinks: false} %></li>
      <li>内容: <%= item.content %></li>
      <li>TPO: <%= item.tpo %></li>
      <li><i class="fa fa-leaf" aria-hidden="true"></i>季節: <%= item.season %></li>
      <li><i class="fa fa-trophy" aria-hidden="true"></i>評価:<span class="star5_rating" data-rate=<%= item.rating %>></span></li>
      <% unless item.cordinate_id.blank? %>
      <li><%= link_to "アイテムのコーデ" , cordinate_show_path( user_id: item.user_id, id: item.cordinate_id ), data: {turbolinks: false} %></li>
      <% else %>
      <li>コーデなしです</li>
      <% end %>
    </uL>
  </div>
</div>
<% end %>

app/views/items/index.html.erb
<!--pathに"/"を含む時は表示させない-->

<li><%#= link_to "アイテム一覧",            catalog_item_path(user_id: params[:user_id])%> </li>
<li><%#= link_to "コーデ一覧",              catalog_cordinate_path(user_id: params[:user_id])%></li>
<li>
  <%#= link_to "あたらしい服を登録",      show_item_path(user_id: params[:user_id])         unless request.path.include?("/") %>
</li>
<li><%#= link_to "あたらしいコーデを登録",  cordinate_new_path(user_id: params[:user_id])     unless request.path.include?("/")  %>
</li>

<h3>アイテム一覧</h3>

<% @items.sample(6).each do |item| %>
    <div class="image_box text-center">
      <%= link_to image_tag( item.picture.url), item_show_path( user_id: item.user_id, id: item.id), data: {turbolinks: false} unless item.picture.blank? %>
    </div>
    <ul>
      <li>ID: <%= item.id %></li>
      <li>内容: <%= item.content %></li>
      <li>TPO: <%= item.tpo %></li>
      <li><i class="fa fa-leaf" aria-hidden="true"></i>季節: <%= item.season %></li>
     <li><i class="fa fa-trophy" aria-hidden="true"></i>評価:<span class="star5_rating" data-rate= <%= item.rating %> ></span></li>       
    </ul>
<% end %>

<%= will_paginate @items, renderer: TailwindLinkRenderer %>
<div class="mb-4">
  <%= link_to "新規アイテム作成", new_item_path, class: "px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600" %>
</div>

<%# Items index view with search %>
<div class="mb-4">
  <%= form_with url: items_path, method: :get, local: false, data: { turbo_frame: "itemsList" } do |f| %>
    <%= f.label :query, "Search Items", class: "block text-gray-700" %>
    <%= f.text_field :query, class: "w-full p-2 border rounded", placeholder: "Search by name...", data: { controller: "live-search", live_search_target: "input", action: "input->live-search#autoSubmit" } %>
    <%= f.submit "Search", class: "mt-2 px-4 py-2 bg-green-500 text-white rounded hover:bg-green-600" %>
  <% end %>
</div>

<div class="mb-4">
  <button data-action="click->filter#toggle" class="px-4 py-2 bg-gray-500 text-white rounded hover:bg-gray-600">
    フィルター表示 / 非表示
  </button>
</div>
<div data-controller="filter" data-filter-target="panel" class="hidden mb-4">
  <h2 class="text-lg font-semibold mb-2">フィルターオプション</h2>
  <%= form_with url: items_path, method: :get, local: false, data: { turbo_frame: "itemsList" } do |f| %>
    <div class="mb-4">
      <%= f.label :season, "季節", class: "block text-gray-700" %>
      <%= f.select :season, options_for_select(Item.seasons.keys), { include_blank: true }, { class: "w-full p-2 border rounded" } %>
    </div>
    <div class="mb-4">
      <%= f.label :super_item, "カテゴリー", class: "block text-gray-700" %>
      <%= f.select :super_item, options_for_select(Item.super_items.keys), { include_blank: true }, { class: "w-full p-2 border rounded" } %>
    </div>
    <div class="mb-4">
      <%= f.label :sort, "並び替え", class: "block text-gray-700" %>
      <%= f.select :sort, options_for_select([["名前昇順", "name_asc"], ["名前降順", "name_desc"], ["評価（高→低）", "rating_desc"], ["評価（低→高）", "rating_asc"]]), { include_blank: true }, { class: "w-full p-2 border rounded" } %>
    </div>
    <%= f.submit "フィルター適用", class: "px-4 py-2 bg-green-500 text-white rounded hover:bg-green-600" %>
  <% end %>
  <div class="mt-2">
    <%= link_to "フィルターリセット", items_path, class: "px-4 py-2 bg-gray-500 text-white rounded hover:bg-gray-600", data: { turbo_frame: "itemsList" } %>
  </div>
</div>

<div class="mb-4">
  <p class="text-gray-700">検索結果: <%= @items.total_entries %> 件</p>
</div>

<turbo-frame id="itemsList">
  <h1 class="text-2xl font-bold mb-4">Items List</h1>
  <div class="space-y-4">
    <% @items.each do |item| %>
      <div class="flex items-center justify-between border p-2 rounded" data-item-id="<%= item.id %>">
        <%= link_to item.name, item_path(item), class: "text-gray-800 hover:underline" %>
        <%= link_to "削除", item_path(item), data: { action: "click->confirm-delete#confirm" }, method: :delete, class: "text-red-500 hover:underline" %>
      </div>
    <% end %>
  </div>
  <%= render 'shared/modal' %>
</turbo-frame>

app/views/items/show.html.erb
<h1 class="text-2xl font-bold mb-4"><%= @item.name %> の詳細</h1>

<div class="bg-white shadow rounded p-4">
  <% if @item.picture.present? %>
    <div class="mb-4">
      <%= image_tag @item.picture.url, class: "w-full rounded" %>
    </div>
  <% end %>
  <ul class="space-y-2">
    <li><strong>内容:</strong> <%= @item.content %></li>
    <li><strong>TPO:</strong> <%= @item.tpo %></li>
    <li><strong>季節:</strong> <%= @item.season %></li>
    <li><strong>評価:</strong> <%= @item.rating %></li>
  </ul>
</div>

<div class="mt-4 flex space-x-4">
  <%= link_to "編集", edit_item_path(@item), class: "px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600" %>
  <%= link_to "削除", item_path(@item), data: { action: "click->confirm-delete#confirm" }, method: :delete, class: "px-4 py-2 bg-red-500 text-white rounded hover:bg-red-600" %>
</div>

<div class="item_show_lists ">
  <ul>
    <li>ユーザー: <%=link_to @item.user.name, user_show_path(id: params[:user_id]), data: {turbolinks: false} %></li>
    <li>カテゴリー ：<%= @item.super_item %></li>
    <li><i class="fa fa-leaf" aria-hidden="true"></i>季節： <%= @item.season %></li>
    <li>TPO :<%= @item.tpo %></li>
    <li>内容： <%= @item.content %></li>
    <li>カラー： <%= @item.color %></li>
    <li><i class="far fa-edit fa-1x"></i>メモ： <%= @item.memo %></li>
    <!--星評価-->
    <li><i class="fa fa-trophy" aria-hidden="true"></i>評価:<span class="star5_rating" data-rate=<%= @item.rating %>></span></li>
    <li><%= link_to "アイテムのコーデをみてみる" , cordinate_show_path( user_id: @item.user_id, id: @item.cordinate_id ) , data: {turbolinks: false} unless @item.cordinate_id.blank? %></li>
  </ul>
</div>
</div>

<% if @item.super_item == "suits" %>
<%= link_to "コーデにスーツとして登録",    cordinate_new_path( cordinate_si_suits:   params[:id], item_id: @item.id), data: {turbolinks: false} %>
　　　<% elsif @item.super_item == "outer" %>
　　　 <%= link_to "コーデにアウターとして登録",cordinate_new_path( cordinate_si_outer:   params[:id], item_id: @item.id, data: {turbolinks: false}) %>
　　　<% elsif @item.super_item == "tops"  %>
　　　 <%= link_to "コーデにトップスとして登録",  cordinate_new_path( cordinate_si_tops:    params[:id], item_id: @item.id), data: {turbolinks: false} %>
　　　<% elsif  @item.super_item == "bottoms" %>
<%= link_to "コーデにボトムスとして登録",  cordinate_new_path( cordinate_si_bottoms: params[:id], item_id: @item.id), data: {turbolinks: false} %>
<% elsif  @item.super_item == "shoes" %>
<%= link_to "コーデにシューズとして登録",  cordinate_new_path( cordinate_si_shoes:   params[:id], item_id: @item.id), data: {turbolinks: false} %>
<% end %>