config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'users#new'
  # root "/LP"
  get '/lp', to: redirect('/lp.html')

  resources :items
  resources :cordinates
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  resources :microposts, only: %i[create destroy]
  resources :relationships, only: %i[create destroy]
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  resources :relationships, only: %i[create destroy]
  resources :blocks, only: %i[create destroy]

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :users do
    member do
      get :blocking, :blockers
    end
  end

  delete '/logout', to: 'sessions#destroy'
  get 'search', to: 'items#search'
  get '/help', to: 'static_pages#help'
  get '/home', to: 'static_pages#home'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  # かんたんログインの実装
  post '/sessions/guest_log_in', to: 'sessions#guest_login', as: 'guest_login'
  # 全てのUserのItemとCordinateをみる
  get '/:user_id/cordinates/allusers', to: 'cordinates#all_cordinate_show',
                                       as: 'all_cordinate_show'
  get '/:user_id/items/allusers', to: 'items#all_item_show', as: 'all_item_show'

  # Rasnsackで全てのUserのItemをみる
  get '/:user_id/items/items_search/tpo', to: 'items#all_item_tpo_search',
                                          as: 'items_tpo_search'
  get '/:user_id/items/items_search/rating',
      to: 'items#all_item_rating_search', as: 'items_rating_search'
  get '/:user_id/items/items_search/season',
      to: 'items#all_item_season_search', as: 'items_serch_season'
  get '/:user_id/items/items_search/color', to: 'items#all_item_color_search',
                                            as: 'items_search_color'
  get '/:user_id/items/items_search/super_item',
      to: 'items#all_item_super_item_search', as: 'items_search_super_item'

  # Rasnsackで全てのUserのCordinateをみる
  get '/:user_id/cordinates/cordinates_search/tpo', to: 'cordinates#all_cordinate_tpo_search',
                                                    as: 'cordinates_tpo_search'
  get '/:user_id/cordinates/cordinates_search/season', to: 'cordinates#all_cordinate_season_search',
                                                       as: 'cordinates_season_search'
  get '/:user_id/cordinates/cordinates_search/rating', to: 'cordinates#all_cordinate_rating_search',
                                                       as: 'cordinates_rating_search'

  get '/:user_id/items/cordinates_search',
      to: 'cordinates#all_cordinate_search', as: 'cordinates_serch'

  # userコントローラー
  get '/users/:user_id/index', to: 'users#index', as: 'allusers_index'
  get '/users/new', to: 'users#new', as: 'user_new'
  get '/users/:id/', to: 'users#show', as: 'user_show'
  # get '/users/:id/ranking', to: 'users#ranking', as: 'user_ranking'

  # itemsコントローラー(個別User)
  get '/users/:user_id/items/all', to: 'items#user_all_item_show',
                                   as: 'user_item'
  get '/users/:user_id/items/new', to: 'items#new', as: 'item_new'
  get '/users/:user_id/items/:id', to: 'items#show', as: 'item_show'
  patch '/users/:user_id/items/:id/edit', to: 'items#update', as: 'item_update'
  get '/users/:user_id/items/:id/edit', to: 'items#edit', as: 'item_edit'
  get '/users/:user_id/cordinates/:cordinate_id/items',
      to: 'items#cordinate_show', as: 'cordinate_item_show'
  get '/users/:user_id/cordinates/:cordinate_id/items/search', to: 'items#cordinate_search_si',
                                                               as: 'cordinate_search_si'
  post '/users/:user_id/items/', to: 'items#create', as: 'item_create'
  delete '/users/:user_id/items/:id', to: 'items#destroy', as: 'item_delete'

  # cordinateコントローラー(個別のUser)
  get '/users/:user_id/cordinates/all',
      to: 'cordinates#user_all_cordinate_show', as: 'user_cordinate'
  get '/users/:user_id/cordinates/new', to: 'cordinates#new', as: 'cordinate_new'
  get '/users/:user_id/cordinates/:id', to: 'cordinates#show',
                                        as: 'cordinate_show'
  get '/users/:user_id/cordinates/:id/edit', to: 'cordinates#edit',
                                             as: 'cordinate_edit'
  post '/users/:user_id/cordinates/', to: 'cordinates#create',
                                      as: 'cordinate_create'

  # get '/users/:user_id/cordinates/:id/modal', to: 'cordinates#cordinate_modal',

  # saveに関してリファクタリングの可能性を検討する
  get '/users/:user_id/cordinates/:id/items/:item_id/edit',
      to: 'cordinates#item_edit', as: 'cordinate_item_edit'

  # controllerを変える必要はあるのか？
  patch '/users/:user_id/cordinates/:id/', to: 'cordinates#update',
                                           as: 'cordinate_patch'
  delete '/users/:user_id/cordinates/:id', to: 'cordinates#destroy',
                                           as: 'cordinate_delete'
  patch '/users/:user_id/cordinates/:id/items/:item_id',
        to: 'cordinates#item_update', as: 'items_patch'

  # Commentシリーズ(個別のUser)
  post '/users/:user_id/cordinates/:id/comments', to: 'comments#create',
                                                  as: 'comment_create'
  delete '/users/:user_id/cordinates/:id/comments/:comment_id',
         to: 'comments#destroy', as: 'comment_delete'

  # Likecordinateシリーズ(個別のUser)
  post '/users/:user_id/cordinates/:id/likecordinates',
       to: 'likecordinates#create', as: 'likecordinate_create'
  delete '/users/:user_id/cordinates/:id/likecordinates/:likecordinate_id', to: 'likecordinates#destroy',
                                                                            as: 'likecordinate_delete'
  # Notificationsコントローラー(個別のUser)
  get '/users/:user_id/notifications/', to: 'notifications#index',
                                        as: 'notifications'
  delete '/users/notifications/alldelete', to: 'notifications#destroy_all',
                                           as: 'destroy_all_users_notifications'
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
<%= content_tag(:p, value, class: "alert alert-#{key}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="bg-gray-800 text-white py-4">
  <div class="max-w-7xl mx-auto px-4 text-center">
    <p class="text-sm">&copy; <%= Time.current.year %> スピウェア. All Rights Reserved.</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="header-logo">
  <%= image_tag "speadwear.png", size: '80x80', class: "site-logo" %>
  <h2>スピウェア</h2>
  <div class="whether_position">
    <%= render "shared/whether_report" %>
  </div>
</div>



<nav class="navbar navbar-expand-lg navbar-light is-hidden" style="background-color: #edfad7;">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav ">
      <%= link_to 'トップページ', root_path,class: "p-2 text-muted", data: {turbolinks: false} %>
      <% unless logged_in? %>
      <%= link_to "ログイン", login_path, class: "p-2 text-muted", data: {turbolinks: false} %>
      <%= link_to '新規登録', signup_path , class: "p-2 text-muted", data: {turbolinks: false} %>
      <% end %>
      <%# unless request.path.include?("/signup") || request.path.include?("/login")   %>
      <% if logged_in? %>
      <%= link_to "プロフィール編集", edit_user_path(current_user),class: "p-2 text-muted", data: {turbolinks: false} %>
      <%= link_to "ログアウト", logout_path, method: :delete, class: "p-2 text-muted", data: {turbolinks: false} %>
      <% end %>
      <% unless session[:user_id] == nil %>

      <%= link_to "ユーザー表示", allusers_index_path(user_id: session[:user_id]), class: "p-2 text-muted", data: {turbolinks: false}  %>
      <%= link_to "みんなのアイテム", all_item_show_path(user_id: session[:user_id]), class: "p-2 text-muted", data: {turbolinks: false} %>
      <%= link_to "みんなのコーデ", all_cordinate_show_path(user_id: session[:user_id]), class: "p-2 text-muted", data: {turbolinks: false}  %>
      <%= link_to "マイアイテム", user_item_path(user_id: session[:user_id]), class: "p-2 text-muted", data: {turbolinks: false}  %>
      <%= link_to "マイコーデ", user_cordinate_path(user_id: session[:user_id]), class: "p-2 text-muted", data: {turbolinks: false}  %>
      <%= link_to "アイテム作成", item_new_path(user_id: session[:user_id]), class: "p-2 text-muted", data: {turbolinks: false}  %>
      <%= link_to "コーデ作成", cordinate_new_path(user_id: session[:user_id]), class: "p-2 text-muted", data: {turbolinks: false} %>
      <%= link_to "通知りれき", notifications_path(user_id: session[:user_id]), class: "p-2 text-muted", data: {turbolinks: false} %>
      <% end %>
    </div>
  </div>
</nav>

<div id="nav-toggle">
  メニュー
  <div>
    <span></span>
    <span></span>
    <span></span>
  </div>
</div>


<div id="gloval-nav">
  <nav>
    <div class="navbar-nav ">
      <li><%= link_to 'トップページ', root_path, data: {turbolinks: false} %></li>
      <% unless logged_in? %>
      <li><%= link_to "ログイン", login_path, data: {turbolinks: false} %></li>
      <li><%= link_to '新規登録', signup_path , data: {turbolinks: false} %></li>
      <% end %>
      <% if logged_in? %>
      <%= link_to "プロフィール編集", edit_user_path(current_user), data: {turbolinks: false} %></li>
      <li><%= link_to "ログアウト", logout_path, method: :delete, data: {turbolinks: false} %></li>
      <% end %>
      <% unless session[:user_id] == nil %>
      <li><%= link_to "ユーザー表示", allusers_index_path(user_id: session[:user_id]), data: {turbolinks: false}  %></li>
      <li><%= link_to "みんなのアイテム", all_item_show_path(user_id: session[:user_id]), data: {turbolinks: false} %></li>
      <li><%= link_to "みんなのコーデ", all_cordinate_show_path(user_id: session[:user_id]), data: {turbolinks: false}%></li>
      <li><%= link_to "マイアイテム", user_item_path(user_id: session[:user_id]), data: {turbolinks: false}  %></li>
      <li><%= link_to "マイコーデ", user_cordinate_path(user_id: session[:user_id]), data: {turbolinks: false}  %></li>
      <li><%= link_to "アイテム作成", item_new_path(user_id: session[:user_id]), data: {turbolinks: false}  %></li>
      <li><%= link_to "コーデ作成", cordinate_new_path(user_id: session[:user_id]), data: {turbolinks: false} %></li>
      <li><%= link_to "通知りれき", notifications_path(user_id: session[:user_id]), data: {turbolinks: false} %></li>
      <% end %>
  </nav>
</div><!-- /#gloval-nav -->

<div id="container">
</div>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.12.3/jquery.min.js"></script>
<script type="text/javascript">
  (function($) {
    $(function() {
      $('#nav-toggle').on('click', function() {
        $('body').toggleClass('open');
      });
    });
  })(jQuery);
</script>

app/views/layouts/_sidemenu.html.erb
<div class="bg-gray-100 min-h-screen p-4">
  <ul class="space-y-2">
    <li>
      <%= link_to 'ホーム', root_path, class: "block px-4 py-2 text-gray-700 hover:bg-gray-200 rounded" %>
    </li>
    <li>
      <%= link_to 'アイテム一覧', items_path, class: "block px-4 py-2 text-gray-700 hover:bg-gray-200 rounded" %>
    </li>
    <li>
      <%= link_to 'コーデ一覧', cordinates_path, class: "block px-4 py-2 text-gray-700 hover:bg-gray-200 rounded" %>
    </li>
    <li>
      <%= link_to 'ユーザー一覧', users_path, class: "block px-4 py-2 text-gray-700 hover:bg-gray-200 rounded" %>
    </li>
  </ul>
</div>

<p class=item_heading>アイテムから探す</p>

<div class="accordion" id="accordionExample">
  <div class="card">
    <div class="card-header" id="headingOne">
      <h2 class="mb-0">
        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          季節から
        </button>
      </h2>
    </div>
    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
      <div class="card-body">
        <% if @q_item_season.nil?  %>
        選択できません。
        <% else %>
        <nav class="nav flex-column">
          <%= link_to '春',{:controller=>"items",:action=>"all_item_season_search", :q_season=>{:season_eq=>'0'}} %>
          <%= link_to '夏',{:controller=>"items",:action=>"all_item_season_search", :q_season=>{:season_eq=>'1'}} %>
          <%= link_to '秋',{:controller=>"items",:action=>"all_item_season_search", :q_season=>{:season_eq=>'2'}} %>
          <%= link_to '冬',{:controller=>"items",:action=>"all_item_season_search", :q_season=>{:season_eq=>'3'}} %>
        </nav>
        <% end %>
      </div>
    </div>

    <div class="card">
      <div class="card-header" id="headingTwo">
        <h2 class="mb-0">
          <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
            TPOから
          </button>
        </h2>
      </div>
      <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
        <div class="card-body">
          　<% if @q_item_tpo.nil?  %>
          選択できません。
          <% else %>
          <nav class="nav flex-column">
            <%= link_to 'デート',    {:controller=>"items",:action=>"all_item_tpo_search",:q_tpo=>{:tpo_eq=>'0'}}   %>
            <%= link_to 'リラックス',  {:controller=>"items",:action=>"all_item_tpo_search",:q_tpo=>{:tpo_eq=>'1'}}  %>
            <%= link_to 'スポーツ',  {:controller=>"items",:action=>"all_item_tpo_search",:q_tpo=>{:tpo_eq=>'2'}}    %>
            <%= link_to 'おでかけ'  ,{:controller=>"items",:action=>"all_item_tpo_search",:q_tpo=>{:tpo_eq=>'3'}}    %>
            <%= link_to '仕事',      {:controller=>"items",:action=>"all_item_tpo_search",:q_tpo=>{:tpo_eq=>'4'}}   %>
          </nav>
          <% end %>
        </div>
      </div>
    </div>


    <div class="card">
      <div class="card-header" id="headingThree">
        <h2 class="mb-0">
          <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
            評価から
          </button>
        </h2>
      </div>
      <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
        <div class="card-body">

          <% if @q_item_rating.nil?  %>
          選択できません。
          <% else %>
          <nav class="nav flex-column">
            <%= link_to '☆',    {:controller=>"items",:action=>"all_item_rating_search",:q_rating=>{:rating_eq=>'0'}}%>
            <%= link_to '☆☆',   {:controller=>"items",:action=>"all_item_rating_search",:q_rating=>{:rating_eq=>'1'}}%>
            <%= link_to '☆☆☆',  {:controller=>"items",:action=>"all_item_rating_search",:q_rating=>{:rating_eq=>'2'}}%>
            <%= link_to '☆☆☆☆', {:controller=>"items",:action=>"all_item_rating_search",:q_rating=>{:rating_eq=>'3'}}%>
            <%= link_to '☆☆☆☆☆',{:controller=>"items",:action=>"all_item_rating_search",:q_rating=>{:rating_eq=>'4'}}%>
          </nav>
          <% end %>
        </div>
      </div>
    </div>
    <div class="card">
      <div class="card-header" id="headingFive">
        <h2 class="mb-0">
          <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
            カラー検索
          </button>
        </h2>
      </div>


      <% if  @q_item_color.nil?  %>
      選択できません。
      <% else %>
      <div id="collapseFive" class="collapse" aria-labelledby="headingFive" data-parent="#accordionExample">
        <div class="card-body">
          <nav class="nav flex-column">
            <div class="color_list">
              <ul>
                <li>
                  <div class="color-black">
                    <%= link_to 'Black',      {:controller=>"items",:action=>"all_item_color_search",:q_color=>{:color_eq=> '0'}}%>
                  </div>
                </li>
                <li>
                  <div class="color-white">
                    <%= link_to 'White',      {:controller=>"items",:action=>"all_item_color_search",:q_color=>{:color_eq=> '1'}}%>
                  </div>
                </li>
                <li>
                  <div class="color-gray">
                    <%= link_to 'Gray',       {:controller=>"items",:action=>"all_item_color_search",:q_color=>{:color_eq=> '2'}}%>
                  </div>
                </li>
                <li>
                  <div class="color-red">
                    <%= link_to 'Red',        {:controller=>"items",:action=>"all_item_color_search",:q_color=>{:color_eq=> '3'}}%>
                  </div>
                </li>
                <li>
                  <div class="color-navy">
                    <%= link_to 'Navy',       {:controller=>"items",:action=>"all_item_color_search",:q_color=>{:color_eq=> '4'}}%>
                  </div>
                </li>
                <li>
                  <div class="color-lightblue">
                    <%= link_to 'Light Blue', {:controller=>"items",:action=>"all_item_color_search",:q_color=>{:color_eq=> '5'}}%>
                  </div>
                </li>
                <li>
                  <div class="color-yellow">
                    <%= link_to 'Yellow',     {:controller=>"items",:action=>"all_item_color_search",:q_color=>{:color_eq=> '6'}}%>
                  </div>
                </li>
                <li>
                  <div class="color-green">
                    <%= link_to 'Green',      {:controller=>"items",:action=>"all_item_color_search",:q_color=>{:color_eq=> '7'}}%>
                  </div>
                </li>
                <li>
                  <div class="color-orenge">
                    <%= link_to 'Orenge',     {:controller=>"items",:action=>"all_item_color_search",:q_color=>{:color_eq=> '8'}}%>
                  </div>
                </li>
                <li>
                  <div class="color-olive">
                    <%= link_to 'Olive',      {:controller=>"items",:action=>"all_item_color_search",:q_color=>{:color_eq=> '9'}}%>
                  </div>
                </li>
                <li>
                  <div class="color-neon">
                    <%= link_to 'Neon',       {:controller=>"items",:action=>"all_item_color_search",:q_color=>{:color_eq=> '10'}}%>
                  </div>
                </li>
                <li>
                  <div class="color-border">
                    <%= link_to 'Border',     {:controller=>"items",:action=>"all_item_color_search",:q_color=>{:color_eq=> '11'}}%>
                  </div>
                </li>
                <li>
                  <div class="color-patternned">
                    <%= link_to 'Patternned', {:controller=>"items",:action=>"all_item_color_search",:q_color=>{:color_eq=> '12'}}%>
                  </div>
                </li>
                <li>
                  <div class="color-denim">
                    <%= link_to 'Denim',      {:controller=>"items",:action=>"all_item_color_search",:q_color=>{:color_eq=> '13'}}%>
                  </div>
                </li>
                <div class="color-othercolor">
                  <%= link_to 'Others',      {:controller=>"items",:action=>"all_item_color_search",:q_color=>{:color_eq=> '14'}}%>
                </div>
                </li>
              </ul>
            </div>
        </div>
      </div>
      </nav>
      <% end%>


    </div>
  </div>

  <div class="card">
    <div class="card-header" id="headingSix">
      <h2 class="mb-0">
        <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseSix" aria-expanded="false" aria-controls="collapseSix">
          カテゴリーから
        </button>
      </h2>
    </div>
    <% if @q_item_super_item.nil?  %>
    選択できません。
    <% else %>
    <div id="collapseSix" class="collapse" aria-labelledby="headingSix" data-parent="#accordionExample">
      <div class="card-body">
        <nav class="nav flex-column">
          <%= link_to 'アウター', {:controller=>"items",:action=>"all_item_super_item_search",:q_super_item=>{:super_item_eq=>'0'}}%>
          <%= link_to 'トップス', {:controller=>"items",:action=>"all_item_super_item_search",:q_super_item=>{:super_item_eq=>'1'}}%>
          <%= link_to 'ボトムス', {:controller=>"items",:action=>"all_item_super_item_search",:q_super_item=>{:super_item_eq=>'2'}}%>
          <%= link_to 'シューズ', {:controller=>"items",:action=>"all_item_super_item_search",:q_super_item=>{:super_item_eq=>'3'}}%>
        </nav>
      </div>
    </div>
    <% end %>
  </div>
</div>


<!--Cordinate版-->

<p class=item_heading>コーデから探す</p>

<div class="accordion" id="accordionExample">
  <div class="card">
    <div class="card-header" id="headingSeven">
      <h2 class="mb-0">
        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseSeven" aria-expanded="true" aria-controls="collapseSeven">
          季節から
        </button>
      </h2>
    </div>
    <div id="collapseSeven" class="collapse show" aria-labelledby="headingSeven" data-parent="#accordionExample">
      <div class="card-body flex-column"">
<% if @p_cordinate_season.nil?  %>
   選択できません。
          <% else %>
        <nav class=" nav flex-column card-body">
        <%= link_to '春',{:controller=>"cordinates",:action=>"all_cordinate_season_search", :p_season=>{:season_eq=>'0'}}%>
        <%= link_to '夏',{:controller=>"cordinates",:action=>"all_cordinate_season_search", :p_season=>{:season_eq=>'1'}}%>
        <%= link_to '秋',{:controller=>"cordinates",:action=>"all_cordinate_season_search", :p_season=>{:season_eq=>'2'}}%>
        <%= link_to '冬',{:controller=>"cordinates",:action=>"all_cordinate_season_search", :p_season=>{:season_eq=>'3'}}%>
        </nav>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card">
    <div class="card-header" id="headingEight">
      <h2 class="mb-0">
        <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseEight" aria-expanded="false" aria-controls="collapseEight">
          TPOから
        </button>
      </h2>
    </div>
    <% if @p_cordinate_tpo.nil?  %>
    選択できません。
    <% else %>
    <div id="collapseEight" class="collapse" aria-labelledby="headingEight" data-parent="#accordionExample">
      <div class="card-body">
        <nav class="nav flex-column">
          <%= link_to 'デート',    {:controller=>"cordinates",:action=>"all_cordinate_tpo_search",:p_tpo=>{:tpo_eq=>'0'}}%>
          <%= link_to 'リラックス',  {:controller=>"cordinates",:action=>"all_cordinate_tpo_search",:p_tpo=>{:tpo_eq=>'1'}}%>
          <%= link_to 'スポーツ'  ,{:controller=>"cordinates",:action=>"all_cordinate_tpo_search",:p_tpo=>{:tpo_eq=>'2'}}%>
          <%= link_to 'おでかけ',      {:controller=>"cordinates",:action=>"all_cordinate_tpo_search",:p_tpo=>{:tpo_eq=>'3'}}%>
          <%= link_to '仕事',      {:controller=>"cordinates",:action=>"all_cordinate_tpo_search",:p_tpo=>{:tpo_eq=>'4'}}%>
        </nav>
      </div>
    </div>
    <% end%>
  </div>
</div>

<div class="card">
  <div class="card-header" id="headingNine">
    <h2 class="mb-0">
      <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseNine" aria-expanded="false" aria-controls="collapseNine">
        評価から
      </button>
    </h2>
  </div>
  <% if @p_cordinate_rating.nil?  %>
  選択できません。
  <% else %>
  <div id="collapseNine" class="collapse" aria-labelledby="headingNine" data-parent="#accordionExample">
    <div class="card-body">
      <nav class="nav flex-column">
        <%= link_to '☆',    {:controller=>"cordinates",:action=>"all_cordinate_rating_search",:p_rating=>{:rating_eq=>'0'}}%>
        <%= link_to '☆☆',   {:controller=>"cordinates",:action=>"all_cordinate_rating_search",:p_rating=>{:rating_eq=>'1'}}%>
        <%= link_to '☆☆☆',  {:controller=>"cordinates",:action=>"all_cordinate_rating_search",:p_rating=>{:rating_eq=>'2'}}%>
        <%= link_to '☆☆☆☆', {:controller=>"cordinates",:action=>"all_cordinate_rating_search",:p_rating=>{:rating_eq=>'3'}}%>
        <%= link_to '☆☆☆☆☆',{:controller=>"cordinates",:action=>"all_cordinate_rating_search",:p_rating=>{:rating_eq=>'4'}}%>
      </nav>
    </div>
  </div>
  <% end%>

</div>

app/views/layouts/header.html.erb
<header class="bg-white shadow">
  <nav class="container mx-auto px-4 py-2 flex items-center justify-between">
    <div class="text-xl font-semibold">
      <%= link_to 'スピウェア', root_path, class: 'text-gray-800 hover:text-gray-600' %>
    </div>
    <div class="hidden md:flex space-x-4">
      <%= link_to 'Home', root_path, class: 'text-gray-800 hover:text-gray-600' %>
      <%= link_to 'About', about_path, class: 'text-gray-800 hover:text-gray-600' %>
      <%= link_to 'Contact', contact_path, class: 'text-gray-800 hover:text-gray-600' %>
    </div>
    <div class="md:hidden">
      <button id="mobile-menu-button" class="text-gray-800 focus:outline-none">
        <svg class="h-6 w-6 fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
          <path d="M4 6h16M4 12h16M4 18h16" />
        </svg>
      </button>
    </div>
  </nav>
  <div id="mobile-menu" class="hidden md:hidden bg-white shadow">
    <div class="px-4 pt-2 pb-4 space-y-2">
      <%= link_to 'Home', root_path, class: 'block text-gray-800 hover:text-gray-600' %>
      <%= link_to 'About', about_path, class: 'block text-gray-800 hover:text-gray-600' %>
      <%= link_to 'Contact', contact_path, class: 'block text-gray-800 hover:text-gray-600' %>
    </div>
  </div>
  <script>
    document.getElementById('mobile-menu-button').addEventListener('click', function() {
      var menu = document.getElementById('mobile-menu');
      menu.classList.toggle('hidden');
    });
  </script>
</header> 